services:
  db: 
    image: postgres:16-alpine
    container_name: ddbb_momentum
    environment:
      POSTGRES_DB: ddbb_momentum 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: momentum_back
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/ddbb_momentum?user=postgres&password=postgres
      JWT_SECRET_KEY: 33345f5b9fcb3d7aa38d6b6e0eaaabe70d903348d6d0ca60e53841c7f0adf9dc
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
